cd lib
mv geogebra_properties.jar xgeogebra_properties.jar
unzip xgeogebra_properties.jar
zip geogebra_properties.jar geogebra/properties/colors.properties
zip geogebra_properties.jar geogebra/properties/colors_sv.properties
zip geogebra_properties.jar geogebra/properties/colors_fr.properties
zip geogebra_properties.jar geogebra/properties/colors_pl.properties
zip geogebra_properties.jar geogebra/properties/colors_nl.properties
zip geogebra_properties.jar geogebra/properties/colors_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/colors_hi.properties
zip geogebra_properties.jar geogebra/properties/colors_de.properties
zip geogebra_properties.jar geogebra/properties/colors_ru.properties
zip geogebra_properties.jar geogebra/properties/colors_it.properties
zip geogebra_properties.jar geogebra/properties/command.properties
zip geogebra_properties.jar geogebra/properties/command_sv.properties
zip geogebra_properties.jar geogebra/properties/command_fr.properties
zip geogebra_properties.jar geogebra/properties/command_pl.properties
zip geogebra_properties.jar geogebra/properties/command_nl.properties
zip geogebra_properties.jar geogebra/properties/command_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/command_hi.properties
zip geogebra_properties.jar geogebra/properties/command_de.properties
zip geogebra_properties.jar geogebra/properties/command_ru.properties
zip geogebra_properties.jar geogebra/properties/command_it.properties
zip geogebra_properties.jar geogebra/properties/error.properties
zip geogebra_properties.jar geogebra/properties/error_sv.properties
zip geogebra_properties.jar geogebra/properties/error_fr.properties
zip geogebra_properties.jar geogebra/properties/error_pl.properties
zip geogebra_properties.jar geogebra/properties/error_nl.properties
zip geogebra_properties.jar geogebra/properties/error_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/error_hi.properties
zip geogebra_properties.jar geogebra/properties/error_de.properties
zip geogebra_properties.jar geogebra/properties/error_ru.properties
zip geogebra_properties.jar geogebra/properties/error_it.properties
zip geogebra_properties.jar geogebra/properties/javaui.properties
zip geogebra_properties.jar geogebra/properties/javaui_sv.properties
zip geogebra_properties.jar geogebra/properties/javaui_fr.properties
zip geogebra_properties.jar geogebra/properties/javaui_pl.properties
zip geogebra_properties.jar geogebra/properties/javaui_nl.properties
zip geogebra_properties.jar geogebra/properties/javaui_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/javaui_hi.properties
zip geogebra_properties.jar geogebra/properties/javaui_de.properties
zip geogebra_properties.jar geogebra/properties/javaui_ru.properties
zip geogebra_properties.jar geogebra/properties/javaui_it.properties
zip geogebra_properties.jar geogebra/properties/menu.properties
zip geogebra_properties.jar geogebra/properties/menu_sv.properties
zip geogebra_properties.jar geogebra/properties/menu_fr.properties
zip geogebra_properties.jar geogebra/properties/menu_pl.properties
zip geogebra_properties.jar geogebra/properties/menu_nl.properties
zip geogebra_properties.jar geogebra/properties/menu_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/menu_hi.properties
zip geogebra_properties.jar geogebra/properties/menu_de.properties
zip geogebra_properties.jar geogebra/properties/menu_ru.properties
zip geogebra_properties.jar geogebra/properties/menu_it.properties
zip geogebra_properties.jar geogebra/properties/plain.properties
zip geogebra_properties.jar geogebra/properties/plain_sv.properties
zip geogebra_properties.jar geogebra/properties/plain_fr.properties
zip geogebra_properties.jar geogebra/properties/plain_pl.properties
zip geogebra_properties.jar geogebra/properties/plain_nl.properties
zip geogebra_properties.jar geogebra/properties/plain_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/plain_hi.properties
zip geogebra_properties.jar geogebra/properties/plain_de.properties
zip geogebra_properties.jar geogebra/properties/plain_ru.properties
zip geogebra_properties.jar geogebra/properties/plain_it.properties
zip geogebra_properties.jar geogebra/properties/symbols.properties
zip geogebra_properties.jar geogebra/properties/symbols_sv.properties
zip geogebra_properties.jar geogebra/properties/symbols_fr.properties
zip geogebra_properties.jar geogebra/properties/symbols_pl.properties
zip geogebra_properties.jar geogebra/properties/symbols_nl.properties
zip geogebra_properties.jar geogebra/properties/symbols_nl_BE.properties
zip geogebra_properties.jar geogebra/properties/symbols_de.properties
zip geogebra_properties.jar geogebra/properties/symbols_ru.properties
zip geogebra_properties.jar geogebra/properties/symbols_it.properties
rm xgeogebra_properties.jar
rm -rf geogebra
rm -rf META-INF
cd ..
