/*
 * Copyright (C) 2010 Lalit Pant <pant.lalit@gmail.com>
 *
 * The contents of this file are subject to the GNU General Public License
 * Version 3 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.gnu.org/copyleft/gpl.html
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 */

package net.kogics.kojo.codex;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.File;
import java.net.URI;

import javax.swing.JComboBox;

import net.kogics.kojo.core.KojoCtx;
import net.kogics.kojo.core.SCanvas;
import net.kogics.kojo.util.Utils;

/**
 *
 * @author lalit
 */
public class CodeExchangeForm extends javax.swing.JDialog {

    private SCanvas canvas;
    private String code;
    private Talker talker;
    KojoCtx kojoCtx;

    public String email() {
    	return "";
    }

    public String password() {
    	return "";
    }
    
    public void storeIdPass(String id, String pass) {
    	
    }
    
    /** Creates new form CodeExchangeForm */
    public CodeExchangeForm(KojoCtx kojoCtx, boolean modal) {
        super(kojoCtx.frame(), modal);
        this.kojoCtx = kojoCtx;
        initComponents();
        initLoginInfo(email(), password());
        catLabel.setVisible(false);
        catData.setVisible(false);
        cancelButton.setEnabled(false);
    }

    public void centerScreen() {
        Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2,
                (dim.height - abounds.height) / 2);
        super.setVisible(true);
        requestFocus();
    }

    public void initLoginInfo(String email, String password) {
        this.email.setText(email);
        this.password.setText(password);
    }

    public void setCanvas(SCanvas canvas) {
        this.canvas = canvas;
    }

    public void setCode(String code) {
        this.code = code;
        if (code == null || code.trim().equals("")) {
            uploadButton.setEnabled(false);
            uploadButton1.setEnabled(false);
            talkDetails.setText("There's no code in the Script Editor, so there's nothing to Upload!");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        talkDetails = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        registerLink = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        codexLink = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox();
        catData = new javax.swing.JTextField();
        catLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        uploadButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.title")); // NOI18N

        uploadButton.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.uploadButton.text")); // NOI18N
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        talkDetails.setColumns(20);
        talkDetails.setEditable(false);
        talkDetails.setRows(5);
        jScrollPane1.setViewportView(talkDetails);

        jLabel3.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel3.text")); // NOI18N

        title.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.title.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel1.text")); // NOI18N

        jLabel2.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel2.text")); // NOI18N

        password.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.password.text")); // NOI18N

        email.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.email.text")); // NOI18N

        jLabel5.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel5.text")); // NOI18N

        registerLink.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.registerLink.text")); // NOI18N
        registerLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkMouseClicked(evt);
            }
        });

        jLabel6.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(email)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registerLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.closeButton.text")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel4.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel4.text")); // NOI18N

        codexLink.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.codexLink.text")); // NOI18N
        codexLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        codexLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codexLinkMouseClicked(evt);
            }
        });

        jLabel7.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.jLabel7.text")); // NOI18N

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Competition", "Art", "Programming", "Math" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        catData.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.catData.text")); // NOI18N

        catLabel.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.catLabel.text")); // NOI18N

        cancelButton.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        uploadButton1.setText(Utils.loadString(CodeExchangeForm.class, "CodeExchangeForm.uploadButton1.text")); // NOI18N
        uploadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                .addComponent(uploadButton))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(catLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catData, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(uploadButton1)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(closeButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(codexLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uploadButton)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catLabel))
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(codexLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(cancelButton)
                    .addComponent(uploadButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        talker = new Talker(email.getText(), new String(password.getPassword()), new TalkListener() {

            public void onStart() {
                uploadButton.setEnabled(false);
                uploadButton1.setEnabled(false);
                closeButton.setEnabled(false);
                cancelButton.setEnabled(true);
            }

            public void onEvent(String msg) {
                talkDetails.append(msg);
                talkDetails.append("\n");
            }

            public void onFinish(boolean success) {
                if (!success) {
                    uploadButton.setEnabled(true);
                    uploadButton1.setEnabled(true);
                }
                closeButton.setEnabled(true);
                cancelButton.setEnabled(false);
            }
        });
//        File image = canvas.exportThumbnail("dogo", 150);
        File image = canvas.exportImage("codex");
        talkDetails.setText("");
        talker.upload(title.getText(), (String) category.getSelectedItem(), catData.getText(), code, image);
        image.deleteOnExit();
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    	storeIdPass(email.getText(), new String(password.getPassword()));
        setVisible(false);
        kojoCtx.activateScriptEditor();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void registerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URI(Talker.server() + "/register"));
        } catch (Exception ex) {
        	ex.printStackTrace();
        }
    }//GEN-LAST:event_registerLinkMouseClicked

    private void codexLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codexLinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URI(Talker.server() + "/codeexchange"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_codexLinkMouseClicked

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        if (Talker.Competition().equals(cb.getSelectedItem())) {
            catLabel.setVisible(true);
            catData.setVisible(true);
        } else {
            catLabel.setVisible(false);
            catData.setVisible(false);
        }
    }//GEN-LAST:event_categoryActionPerformed

    private void uploadButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButton1ActionPerformed
        uploadButtonActionPerformed(evt);
    }//GEN-LAST:event_uploadButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        talker.cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField catData;
    private javax.swing.JLabel catLabel;
    private javax.swing.JComboBox category;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel codexLink;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerLink;
    private javax.swing.JTextArea talkDetails;
    private javax.swing.JTextField title;
    private javax.swing.JButton uploadButton;
    private javax.swing.JButton uploadButton1;
    // End of variables declaration//GEN-END:variables
}
